title: Cured by a Nerd
author: Matthew Stewart
email: mstewa@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Cured by a Nerd is a site to help bring tech knowledge to the masses.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
